language: dart
dart:
  - stable
  - dev
before_install:
  - sudo apt-get -y install libc6
script:
  - pub get --packages-dir
  - pub run test
  - pub run test_coverage
  - bash <(curl -s https://codecov.io/bash)