name: bgg_api
description:
  Board Game Geek XML API client (version 2)
  This package was inspired by bgg.dart package, which works with first version of BGG API.
version: 0.7.0
repository: https://github.com/bartektartanus/bgg_api

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  xml: ^6.1.0
  html_unescape: ^2.0.0
  http: ^0.13.4
  meta: ^1.8.0

dev_dependencies:
  analyzer: ^4.2.0
  coverage: ^1.5.0
  pedantic: ^1.11.1
  test: ^1.21.4
