name: bgg_api
description:
  Board Game Geek XML API client (version 2)
  This package was inspired by bgg.dart package, which works with first version of BGG API.
version: 0.3.0-nullsafety
repository: https://github.com/bartektartanus/bgg_api

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  xml: ^5.2.0
  html_unescape: ^2.0.0
  http: ^0.13.3
  meta: ^1.7.0

dev_dependencies:
  test: ^1.16.4
  test_coverage: ^0.5.0
  pedantic: ^1.11.1
